#   ____                       _   __  __    ____
#  / ___|   ___     ___     __| | |  \/  |  / ___|
# | |  _   / _ \   / _ \   / _` | | |\/| | | |
# | |_| | | (_) | | (_) | | (_| | | |  | | | |___
#  \____|  \___/   \___/   \__,_| |_|  |_|  \____|
#   ____                       _      _              _     _  __  __
#  / ___|   ___     ___     __| |    / \     _ __   | |_  (_) \ \/ /  _ __    __ _   _   _
# | |  _   / _ \   / _ \   / _` |   / _ \   | '_ \  | __| | |  \  /  | '__|  / _` | | | | |
# | |_| | | (_) | | (_) | | (_| |  / ___ \  | | | | | |_  | |  /  \  | |    | (_| | | |_| |
#  \____|  \___/   \___/   \__,_| /_/   \_\ |_| |_|  \__| |_| /_/\_\ |_|     \__,_|  \__, |
#                                                                                    |___/
# Plugin works with a "Xray Level". 
# The more a player is suspected of using Xray, the more their Xray level value will increase.
# The defaults values in the default configuration have been tested on Minecraft Vanilla 1.13-1.15.
#
# Have a nice game!
Sanction:
 850:
  notify: true
  commands:
   - 'm %player% (ಠ_ಠ) Cheating will lead to blocking! 1/2'
 1000:
  notify: true
  commands:
   - 'm %player% (ಠ益ಠ) Cheating will lead to blocking! 2/2'
   - 'broadcast %player% uses cheats!'
 1200:
  notify: true
  commands:
   - 'kick %player% Cheating will lead to blocking!'
   - 'broadcast %player% was kicked for сheating!'

Prefix:
 primaryColor: '&b&l'
 secondaryColor: '&f'

Messages:
 notify: '&b&l%player%&f&b is suspected of using Xray.'
 check: '&bThe Xray level of &b&l%player%&f&b = %XrayLvl%.'
 playerNotFound: '&bUnable to find this player O_o'
 pluginReloaded: '&bSuccessfully reloaded!'
 cmdUsage: '&bUsage: '
 cmdPlayerOnly: '&bThis command is only for players O_o'
 xrayLvlReset: '&bXray level of &b&l%player%&f&b reseted.'
 xrayLvlSet: '&bXray level of &b&l%player%&f&b set to &b&l%value%&f&b.'