#  #####                              #                       #     #
# #     #   ####    ####   #####     # #    #    #  #####  #   #   #   #####     ##    #   #
# #        #    #  #    #  #    #   #   #   ##   #    #    #    # #    #    #   #  #    # #
# #  ####  #    #  #    #  #    #  #     #  # #  #    #    #     #     #    #  #    #    #
# #     #  #    #  #    #  #    #  #######  #  # #    #    #    # #    #####   ######    #
# #     #  #    #  #    #  #    #  #     #  #   ##    #    #   #   #   #   #   #    #    #
#  #####    ####    ####   #####   #     #  #    #    #    #  #     #  #    #  #    #    #
#
# Plugin works with a "Xray Level".
# The more a player is suspected of using Xray, the more their Xray level value will increase.
# The defaults values in the default configuration have been tested on Minecraft Vanilla 1.13-1.17.
#
# Have a nice game!
Sanction:
 850:
  notify: true # For moderators with permission gax.alerts
  commands:
   - 'm %player% (ಠ_ಠ) Cheating will lead to blocking! 1/2'
 1000:
  notify: true
  commands:
   - 'm %player% (ಠ益ಠ) Cheating will lead to blocking! 2/2'
   - 'broadcast %player% uses cheats!'
 1200:
  notify: true
  commands:
   - 'kick %player% Cheating will lead to blocking!'
   - 'broadcast %player% was kicked for сheating!'

Prefix:
 primaryColor: '&b'
 secondaryColor: '&b&l'

Messages:
 notify: '&b&l%player%&f&b is suspected of using Xray.' # Notify text for moderators with permission gax.alerts
 check: '&bThe Xray level of &b&l%player%&f&b = %XrayLvl%.'
 playerNotFound: '&bUnable to find this player O_o'
 pluginReloaded: '&bSuccessfully reloaded!'
 cmdUsage: '&bUsage: '
 cmdPlayerOnly: '&bThis command is only for players O_o'
 xrayLvlReset: '&bXray level of &b&l%player%&f&b reseted.'
 xrayLvlSet: '&bXray level of &b&l%player%&f&b set to &b&l%value%&f&b.'
